/* global supabase, SAHIMILO_CONFIG */
const db=window.supabase?.createClient(SAHIMILO_CONFIG.supabaseUrl,SAHIMILO_CONFIG.supabasePublishableKey);
let mode="login",method="email",otpSent=false,currentPhone="";const $=id=>document.getElementById(id);
function message(text,ok=false){$("customerMessage").textContent=text;$("customerMessage").className="notice "+(ok?"notice-ok":"notice-error")}
function formatPhone(value){let p=String(value||"").replace(/\D/g,"");if(p.length===10)p="91"+p;return "+"+p}
function refresh(){document.querySelectorAll(".account-tab").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));document.querySelectorAll(".method-tab").forEach(x=>x.classList.toggle("active",x.dataset.method===method));$("nameField").classList.toggle("hidden",mode!=="signup");$("emailFields").classList.toggle("hidden",method!=="email");$("phoneFields").classList.toggle("hidden",method!=="phone");$("customerOtpBox").classList.toggle("hidden",!otpSent);$("customerSubmit").textContent=method==="email"?(mode==="login"?"Login with Email":"Create Email Account"):(otpSent?"Verify OTP":(mode==="login"?"Send Login OTP":"Send Signup OTP"));$("customerPassword").autocomplete=mode==="login"?"current-password":"new-password";$("customerMessage").classList.add("hidden")}
document.querySelectorAll(".account-tab").forEach(tab=>tab.onclick=()=>{mode=tab.dataset.mode;otpSent=false;refresh()});
document.querySelectorAll(".method-tab").forEach(tab=>tab.onclick=()=>{method=tab.dataset.method;otpSent=false;refresh()});
$("customerForm").onsubmit=async e=>{e.preventDefault();const button=$("customerSubmit"),name=$("customerName").value.trim();button.disabled=true;
if(method==="email"){const email=$("customerEmail").value.trim(),password=$("customerPassword").value;if(!email||password.length<8){button.disabled=false;return message("Valid email aur minimum 8-character password enter karein.")}if(mode==="login"){const {error}=await db.auth.signInWithPassword({email,password});button.disabled=false;if(error)return message(error.message);return location.replace("customer-dashboard.html")}if(!name){button.disabled=false;return message("Full name enter karein.")}const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:location.origin+"/customer-dashboard.html"}});button.disabled=false;if(error)return message(error.message);if(data.session)return location.replace("customer-dashboard.html");return message("Account create ho gaya. Email confirmation link open karke login karein.",true)}
currentPhone=formatPhone($("customerPhone").value);if(!/^\+91\d{10}$/.test(currentPhone)){button.disabled=false;return message("Sahi 10-digit Indian mobile number enter karein.")}if(!otpSent){if(mode==="signup"&&!name){button.disabled=false;return message("Full name enter karein.")}const {error}=await db.auth.signInWithOtp({phone:currentPhone,options:{shouldCreateUser:mode==="signup",data:{display_name:name}}});button.disabled=false;if(error)return message(error.message);otpSent=true;refresh();return message("OTP mobile number par bhej diya gaya.",true)}
const token=$("customerOtp").value.trim();const {error}=await db.auth.verifyOtp({phone:currentPhone,token,type:"sms"});button.disabled=false;if(error)return message(error.message);location.replace("customer-dashboard.html")};
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)location.replace("customer-dashboard.html")})();refresh();