/* global supabase, SAHIMILO_CONFIG */
const db=window.supabase?.createClient(SAHIMILO_CONFIG.supabaseUrl,SAHIMILO_CONFIG.supabasePublishableKey),$=id=>document.getElementById(id);let mode="login",method="email",otpSent=false,currentPhone="";
function message(text,ok=false){$("professionalMessage").textContent=text;$("professionalMessage").className="notice "+(ok?"notice-ok":"notice-error")}
function digits(v){return String(v||"").replace(/\D/g,"")}function phone(v){let p=digits(v);if(p.length===10)p="91"+p;return "+"+p}
function draft(){return {name:$("professionalName").value.trim(),phone:phone($("professionalPhone").value),whatsapp:phone($("professionalWhatsapp").value||$("professionalPhone").value),category:$("professionalCategory").value,services:$("professionalServices").value.split(",").map(x=>x.trim()).filter(Boolean),area:$("professionalArea").value.trim(),city:$("professionalCity").value.trim(),state:$("professionalState").value.trim()||"Bihar",pincode:$("professionalPincode").value.trim(),experience_years:0,bio:"",verified_mobile:false,verified_whatsapp:false,verified_by_admin:false,status:"pending"}}
function validDraft(d){return d.name&&digits(d.phone).length>=10&&d.category&&d.services.length&&d.area&&/^\d{6}$/.test(d.pincode)&&d.city}
async function ensureProfile(user){const {data}=await db.from("professionals").select("id").eq("user_id",user.id).maybeSingle();if(data)return true;const saved=localStorage.getItem("sahimiloProfessionalDraft");if(!saved)return false;const {error}=await db.from("professionals").insert({...JSON.parse(saved),user_id:user.id});if(error){message(error.message);return false}localStorage.removeItem("sahimiloProfessionalDraft");return true}
function refresh(){document.querySelectorAll(".account-tab").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));document.querySelectorAll(".method-tab").forEach(x=>x.classList.toggle("active",x.dataset.method===method));$("professionalSignupFields").classList.toggle("hidden",mode!=="signup");$("professionalEmailFields").classList.toggle("hidden",method!=="email");$("professionalPhoneFields").classList.toggle("hidden",method!=="phone");$("professionalOtpBox").classList.toggle("hidden",!otpSent);$("professionalSubmit").textContent=method==="email"?(mode==="login"?"Login with Email":"Create Email Account"):(otpSent?"Verify OTP":(mode==="login"?"Send Login OTP":"Send Signup OTP"));$("professionalPassword").autocomplete=mode==="login"?"current-password":"new-password";$("professionalMessage").classList.add("hidden")}
document.querySelectorAll(".account-tab").forEach(tab=>tab.onclick=()=>{mode=tab.dataset.mode;otpSent=false;refresh()});document.querySelectorAll(".method-tab").forEach(tab=>tab.onclick=()=>{method=tab.dataset.method;otpSent=false;refresh()});
$("professionalForm").onsubmit=async e=>{e.preventDefault();const button=$("professionalSubmit"),d=draft();button.disabled=true;
if(method==="email"){const email=$("professionalEmail").value.trim(),password=$("professionalPassword").value;if(!email||password.length<8){button.disabled=false;return message("Valid email aur minimum 8-character password enter karein.")}if(mode==="login"){const {data,error}=await db.auth.signInWithPassword({email,password});button.disabled=false;if(error)return message(error.message);if(!await ensureProfile(data.user)){await db.auth.signOut();return message("Is account se professional profile linked nahi hai. Create account tab use karein.")}return location.replace("professional-dashboard.html")}if(!validDraft(d)){button.disabled=false;return message("Sabhi professional details sahi se fill karein.")}localStorage.setItem("sahimiloProfessionalDraft",JSON.stringify(d));const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:d.name},emailRedirectTo:location.origin+"/professional-auth.html"}});button.disabled=false;if(error)return message(error.message);if(data.session&&await ensureProfile(data.user))return location.replace("professional-dashboard.html");return message("Account create ho gaya. Email confirm karke isi page par login karein.",true)}
currentPhone=phone($("professionalLoginPhone").value);if(!/^\+91\d{10}$/.test(currentPhone)){button.disabled=false;return message("Sahi 10-digit Indian mobile number enter karein.")}if(!otpSent){if(mode==="signup"){if(!validDraft(d)){button.disabled=false;return message("Sabhi professional details sahi se fill karein.")}localStorage.setItem("sahimiloProfessionalDraft",JSON.stringify(d))}const {error}=await db.auth.signInWithOtp({phone:currentPhone,options:{shouldCreateUser:mode==="signup",data:{display_name:d.name}}});button.disabled=false;if(error)return message(error.message);otpSent=true;refresh();return message("OTP mobile number par bhej diya gaya.",true)}
const token=$("professionalOtp").value.trim();const {data,error}=await db.auth.verifyOtp({phone:currentPhone,token,type:"sms"});button.disabled=false;if(error)return message(error.message);if(!await ensureProfile(data.user)){await db.auth.signOut();return message("Is number se professional profile linked nahi hai. Create account tab use karein.")}location.replace("professional-dashboard.html")};
(async()=>{const {data:{session}}=await db.auth.getSession();if(session&&await ensureProfile(session.user))location.replace("professional-dashboard.html")})();refresh();