/* global supabase, SAHIMILO_CONFIG */
const db=window.supabase?.createClient(SAHIMILO_CONFIG.supabaseUrl,SAHIMILO_CONFIG.supabasePublishableKey),$=id=>document.getElementById(id);let mode="login";
function message(text,ok=false){$("professionalMessage").textContent=text;$("professionalMessage").className="notice "+(ok?"notice-ok":"notice-error")}
function digits(v){return String(v||"").replace(/\D/g,"")}
function phone(v){let p=digits(v);if(p.length===10)p="91"+p;return p?"+"+p:""}
function draft(){return {name:$("professionalName").value.trim(),phone:phone($("professionalPhone").value),whatsapp:phone($("professionalWhatsapp").value||$("professionalPhone").value),category:$("professionalCategory").value,services:$("professionalServices").value.split(",").map(x=>x.trim()).filter(Boolean),area:$("professionalArea").value.trim(),city:$("professionalCity").value.trim(),state:$("professionalState").value.trim()||"Bihar",pincode:$("professionalPincode").value.trim(),experience_years:0,bio:"",verified_mobile:false,verified_whatsapp:false,verified_by_admin:false,status:"pending"}}
function validDraft(d){return d.name&&digits(d.phone).length>=10&&d.category&&d.services.length&&d.area&&/^\d{6}$/.test(d.pincode)&&d.city&&d.state}
async function findProfile(userId){const {data,error}=await db.from("professionals").select("id").eq("user_id",userId).maybeSingle();if(error)throw error;return data}
async function finishLogin(user){try{const existing=await findProfile(user.id);if(existing){localStorage.removeItem("sahimiloProfessionalDraft");localStorage.removeItem("sahimiloProfessionalMode");return location.replace("professional-dashboard.html")}const saved=localStorage.getItem("sahimiloProfessionalDraft");if(saved){const {error}=await db.from("professionals").insert({...JSON.parse(saved),user_id:user.id});if(error)throw error;localStorage.removeItem("sahimiloProfessionalDraft");localStorage.removeItem("sahimiloProfessionalMode");return location.replace("professional-dashboard.html")}await db.auth.signOut();message("Is Google account se professional profile linked nahi hai. Create account tab select karein.")}catch(error){await db.auth.signOut();message(error.message||"Professional account open nahi ho paaya.")}}
function refresh(){document.querySelectorAll(".account-tab").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));$("professionalSignupFields").classList.toggle("hidden",mode!=="signup");$("professionalButtonText").textContent=mode==="signup"?"Create account with Google":"Continue with Google";$("professionalMessage").classList.add("hidden")}
document.querySelectorAll(".account-tab").forEach(tab=>tab.onclick=()=>{mode=tab.dataset.mode;refresh()});
$("professionalForm").onsubmit=async e=>{e.preventDefault();if(mode==="signup"){const d=draft();if(!validDraft(d))return message("Sabhi required professional details sahi se fill karein.");localStorage.setItem("sahimiloProfessionalDraft",JSON.stringify(d))}else localStorage.removeItem("sahimiloProfessionalDraft");localStorage.setItem("sahimiloProfessionalMode",mode);$("professionalSubmit").disabled=true;const {error}=await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+"/professional-auth.html",queryParams:{prompt:"select_account"}}});if(error){$("professionalSubmit").disabled=false;message(error.message)}};
(async()=>{const {data:{session},error}=await db.auth.getSession();if(error)return message(error.message);if(session)await finishLogin(session.user)})();refresh();