-- Common service names and professional-added service catalog
create table if not exists public.professional_service_catalog (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users(id) on delete set null,
  category text not null default 'Other Services',
  service text not null,
  description text not null default 'Local professional dwara available service.',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint professional_service_catalog_service_length check (char_length(trim(service)) between 2 and 80)
);
create unique index if not exists professional_service_catalog_service_lower_idx on public.professional_service_catalog(lower(trim(service)));
alter table public.professional_service_catalog enable row level security;
create policy "anyone reads active professional services" on public.professional_service_catalog for select to anon,authenticated using(active=true);
create policy "professionals add service suggestions" on public.professional_service_catalog for insert to authenticated with check((select auth.uid())=created_by and active=true and category='Other Services');
grant select on public.professional_service_catalog to anon,authenticated;
grant insert on public.professional_service_catalog to authenticated;
grant usage,select on sequence public.professional_service_catalog_id_seq to authenticated;
